services:
  app:
    build:
      context: .
    command: npm run prod
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - internal
      - dragcave

  db:
    image: mariadb:10
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 55554:3306
    networks:
      - internal

volumes:
  dbdata:

networks:
  internal:
  dragcave:
    external: true
