services:
  vue:
    container_name: dc-lb-dev-vue
    build:
      context: .
      dockerfile: ./docker/dev-vue.Dockerfile
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080
    environment:
      - VUE_APP_URL=/
      - VUE_APP_VERSION=${VERSION}
    depends_on:
      - db
      - api
    networks:
      - internal

  api:
    container_name: dc-lb-dev-api
    build:
      context: .
      dockerfile: ./docker/dev-api.Dockerfile
    depends_on:
      - db
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - APP_VERSION=${VERSION}
    networks:
      - internal

  db:
    container_name: dc-lb-dev-db
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - internal

  # only for development
  adminer:
    container_name: dc-lb-dev-adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: lineage_builder
    ports:
      - 82:8080
    networks:
      - internal

volumes:
  dbdata:

networks:
  internal: